stages:
  - endor_scan
  - process_findings

scan_job:
  stage: endor_scan
  script:
    - echo "Running Endor Labs..."
    # Assume the scanning tool outputs its findings to findings.json
    - ./endorctl scan
    - endorctl api list <project just scanned> > output.json

process_findings_job:
  stage: process_findings
  script:
    - echo "Processing findings..."
    - python process_findings.py findings.json
  only:
    - main
